package com.github.smaugfm.util

object MCC {
    val mapRussian = mapOf(
        742 to "Ветеринарные услуги",
        763 to "Сельскохозяйственные кооперативы",
        780 to "Услуги садоводства и ландшафтного дизайна",
        1520 to "Генеральные подрядчики – жилое и коммерческое строительство",
        1711 to "Генеральные подрядчики по вентиляции, теплоснабжению и водопроводу",
        1731 to "Подрядчики по электричеству",
        1740 to "Изоляция, мозаика, штукатурные работы, каменная кладка, облицовка плиткой, кафелем",
        1750 to "Столярные работы",
        1761 to "Кровельные и сайдинговые работы, обработка листового металла",
        1771 to "Подрядчики бетонных работ",
        1799 to "Контрактные услуги – нигде более не классифицированные",
        2741 to "Различные издательства/ печатное дело",
        2791 to "Набор текстов, изготовление печатных форм и связанные услуги",
        2842 to "Санитарная обработка, полировка и специализированная подготовка",
        3000 to "United Airlines (UNITED)",
        3001 to "American Airlines (AMERICAN)",
        3002 to "Pan American (PAN AM)",
        3003 to "Eurofly (EUROFLY)",
        3004 to "Dragonair (DRAGONAIR)",
        3005 to "British Airways (BRITISH A)",
        3006 to "Japan Air Lines (JAL)",
        3007 to "Air France (AIR FRAN)",
        3008 to "Lufthansa (LUFTHAN)",
        3009 to "Air Canada (AIR CAN)",
        3010 to "Royal Dutch Airlines (KLM)",
        3011 to "Aeroflot (AEROFLOT)",
        3012 to "Qantas (QANTAS)",
        3013 to "Alitalia (ALITALIA)",
        3014 to "Saudi Arabian Airlines (SAUDI AI)",
        3015 to "Swiss International Air Lines (SWISS)",
        3016 to "Scandinavian Airline System (SAS)",
        3017 to "South African Airways (SAFRICAN)",
        3018 to "Varig (Brazil) (VARIG)",
        3019 to "Авиалинии, авиакомпании",
        3020 to "Air India (AIR-INDI)",
        3021 to "Air Algerie (AIRALGER)",
        3022 to "Philippine Airlines (PAL AIR)",
        3023 to "Mexicana (MEXICANA)",
        3024 to "Pakistan International (PAKISTAN)",
        3025 to "Air New Zealand Limited International (AIR NZ)",
        3026 to "Emirates Airlines (EMIRATES)",
        3027 to "Union de Transports Aeriens (UTAAIR)",
        3028 to "Air Malta (AIRMALTA)",
        3029 to "SN Brussels Airlines (SNBRU AIR)",
        3030 to "Aerolineas Argentinas (AERO ARG)",
        3031 to "Olympic Airways (OLYMPICA)",
        3032 to "El Al (EL AL)",
        3033 to "Ansett Airlines (ANSETT)",
        3034 to "Etihad Airways (ETIHADAIR)",
        3035 to "Tap (Portugal) (TAP)",
        3036 to "VASP (Brazil) (VASP)",
        3037 to "EgyptAir (EGYPTAIR)",
        3038 to "Kuwait Airways (KUWAIT)",
        3039 to "Avianca (AVIANCA)",
        3040 to "Gulf Air (Bahrain) (GULF AIR)",
        3041 to "Balkan—Bulgarian Airlines (BALKAN)",
        3042 to "Finnair (FINNAIR)",
        3043 to "Aer Lingus (AERLING)",
        3044 to "Air Lanka (AIR LANKA)",
        3045 to "Nigeria Airways (NIGERIA)",
        3046 to "Cruzeiro do Sul (Brazil) (CRUZEIRO)",
        3047 to "Turkish Airlines",
        3048 to "Royal Air Maroc (AIRMARO)",
        3049 to "Tunis Air (TUNIS AI)",
        3050 to "Icelandair (ICELANDA)",
        3051 to "Austrian Airlines (AUSTRIAN)",
        3052 to "LAN Airlines (LAN AIR)",
        3053 to "AVIACO (Spain) (AVIACO)",
        3054 to "LADECO (Chile) (LADECO)",
        3055 to "LAB (Bolivia) (LAB)",
        3056 to "Jet Airways (JET AIR)",
        3057 to "Virgin America (VIR AMER)",
        3058 to "Delta (DELTA)",
        3059 to "DBA Airlines (DBA AIR)",
        3060 to "Northwest Airlines (NWA AIR)",
        3061 to "Continental (CONTINEN)",
        3062 to "Hapag-Lloyd Express (HLX)",
        3063 to "U.S. Airways (USAIRWYS)",
        3064 to "Adria Airways (ADRIA AIR)",
        3065 to "Air Inter (AIRINTER)",
        3066 to "Southwest Airlines (SOUTHWES)",
        3067 to "Vanguard Airlines (VANGUARD)",
        3068 to "Air Astana (AIRSTANA)",
        3069 to "Sun Country Airlines (SUNCNTRY)",
        3071 to "Air British Columbia (AIR B R C)",
        3072 to "Cebu Pacific (CEBU PAC)",
        3073 to "Air Cal",
        3075 to "Singapore Airlines (SINGAPOR)",
        3076 to "Aeromexico (AEROMEXI)",
        3077 to "Thai Airways (THAIAIRW)",
        3078 to "China Airlines (CHINAAIR)",
        3079 to "Jetstar Airways (JETSTAR)",
        3081 to "Авиалинии, авиакомпании",
        3082 to "Korean Airlines (KOREAN)",
        3083 to "Air Afrique (AIR AFRIQ)",
        3084 to "Eva Airways (EVA AIR)",
        3085 to "Midwest Express Airlines (MIDWEST)",
        3086 to "Carnival Airlines",
        3087 to "Metro Airlines (METROAI)",
        3088 to "Croatia Air (CROATIA)",
        3089 to "Transaero (TRANSAERO)",
        3090 to "Uni Airways (UNIAIR)",
        3092 to "Midway Airlines",
        3093 to "Авиалинии, авиакомпании",
        3094 to "Zambia Airways (ZAMBIA A)",
        3095 to "Авиалинии, авиакомпании",
        3096 to "Air Zimbabwe (AIRZIMBA)",
        3097 to "Spanair (SPANAIR)",
        3098 to "Asiana Airlines (ASIANA)",
        3099 to "Cathay Pacific (CATHAYPA)",
        3100 to "Malaysian Airline System (MALAY AI)",
        3101 to "Авиалинии, авиакомпании",
        3102 to "Iberia (IBERIA)",
        3103 to "Garuda (Indonesia) (GARUDA)",
        3104 to "Авиалинии, авиакомпании",
        3105 to "Авиалинии, авиакомпании",
        3106 to "Braathens S.A.F.E. (Norway) (BRAATHEN)",
        3107 to "Авиалинии, авиакомпании",
        3109 to "Авиалинии, авиакомпании",
        3110 to "Авиалинии, авиакомпании",
        3111 to "British Midland (BRITISH M)",
        3112 to "Windward Island (WINDWARD)",
        3113 to "Авиалинии, авиакомпании",
        3114 to "Авиалинии, авиакомпании",
        3115 to "Авиалинии, авиакомпании",
        3116 to "Авиалинии, авиакомпании",
        3117 to "Venezolana International de Aviacion (VIASA)",
        3118 to "Авиалинии, авиакомпании",
        3119 to "Авиалинии, авиакомпании",
        3120 to "Авиалинии, авиакомпании",
        3121 to "Авиалинии, авиакомпании",
        3122 to "Авиалинии, авиакомпании",
        3123 to "Авиалинии, авиакомпании",
        3124 to "Авиалинии, авиакомпании",
        3125 to "Tan Airlines (TAN AIR)",
        3126 to "Авиалинии, авиакомпании",
        3127 to "Taca International (TACA INT)",
        3128 to "Авиалинии, авиакомпании",
        3129 to "Surinam Airways (SURINAM)",
        3130 to "Sunworld International Airways (SUNWORLD)",
        3131 to "VLM Airlines (VLM)",
        3132 to "Frontier Airlines (FRONTIER)",
        3133 to "Авиалинии, авиакомпании",
        3134 to "Авиалинии, авиакомпании",
        3135 to "Авиалинии, авиакомпании",
        3136 to "Qatar Airways Company W.L.L. (QATAR AIR)",
        3137 to "Авиалинии, авиакомпании",
        3138 to "Авиалинии, авиакомпании",
        3139 to "Авиалинии, авиакомпании",
        3140 to "Авиалинии, авиакомпании",
        3141 to "Авиалинии, авиакомпании",
        3142 to "Авиалинии, авиакомпании",
        3143 to "Авиалинии, авиакомпании",
        3144 to "Virgin Atlantic (VIR ATL)",
        3145 to "Авиалинии, авиакомпании",
        3146 to "Luxair (LUXAIR)",
        3147 to "Авиалинии, авиакомпании",
        3148 to "Air Littoral, S.A. (LITTORAL)",
        3150 to "Авиалинии, авиакомпании",
        3151 to "Air Zaire (AIRZAIRE)",
        3152 to "Авиалинии, авиакомпании",
        3153 to "Авиалинии, авиакомпании",
        3154 to "Авиалинии, авиакомпании",
        3155 to "Авиалинии, авиакомпании",
        3156 to "GO FLY Ltd. (GOFLY)",
        3157 to "Авиалинии, авиакомпании",
        3158 to "Авиалинии, авиакомпании",
        3159 to "Provincetown-Boston Airways (PBA)",
        3160 to "Авиалинии, авиакомпании",
        3161 to "All Nippon Airways (ANAAIR)",
        3162 to "Авиалинии, авиакомпании",
        3163 to "Авиалинии, авиакомпании",
        3164 to "Norontair (NORONTAI)",
        3165 to "Авиалинии, авиакомпании",
        3166 to "Авиалинии, авиакомпании",
        3167 to "Aero Continente (AERO CONT)",
        3168 to "Авиалинии, авиакомпании",
        3169 to "Авиалинии, авиакомпании",
        3170 to "Авиалинии, авиакомпании",
        3171 to "Canadian Airlines (CANADIAN)",
        3172 to "Nation Air (NATIONAI)",
        3173 to "Авиалинии, авиакомпании",
        3174 to "JetBlue Airways (JETBLUE)",
        3175 to "Middle East Air (MIDEASTA)",
        3176 to "Авиалинии, авиакомпании",
        3177 to "AirTran Airways (AIRTRAN A)",
        3178 to "Mesa Air (MESA AIR)",
        3179 to "Авиалинии, авиакомпании",
        3180 to "Westjet Airlines (WESTJET)",
        3181 to "Malev Hungarian Airlines (MALEV)",
        3182 to "LOT – Polish Airlines (LOT)",
        3183 to "Oman Aviation Services (OMAN AIR)",
        3184 to "LIAT (LIAT)",
        3185 to "LAV Linea Aeropostal Venezolana (LAV)",
        3186 to "LAP Lineas Aereas Paraguayas (LAP)",
        3187 to "LACSA (Costa Rica) (LACSA)",
        3188 to "Virgin Express (VIR EXP)",
        3189 to "Авиалинии, авиакомпании",
        3190 to "Jugoslav Air (JUGOSLAV)",
        3191 to "Island Airlines (ISLANDAI)",
        3192 to "Авиалинии, авиакомпании",
        3193 to "Indian Airlines (INDIAN A)",
        3194 to "Авиалинии, авиакомпании",
        3195 to "Авиалинии, авиакомпании",
        3196 to "Hawaiian Air (HAWAIIAN)",
        3197 to "Havasu Airlines (HAVASUAI)",
        3198 to "Авиалинии, авиакомпании",
        3199 to "Servicios Aereos Militares",
        3200 to "Guyana Airways (GUYANA A)",
        3201 to "Авиалинии, авиакомпании",
        3202 to "Авиалинии, авиакомпании",
        3203 to "Авиалинии, авиакомпании",
        3204 to "Freedom Airlines (FREEDOM)",
        3205 to "Авиалинии, авиакомпании",
        3206 to "China Eastern Airlines (CHINAEAST)",
        3207 to "Авиалинии, авиакомпании",
        3208 to "Авиалинии, авиакомпании",
        3209 to "Авиалинии, авиакомпании",
        3210 to "Авиалинии, авиакомпании",
        3211 to "Norwegian Air Shuttle (NORWEGIAN)",
        3212 to "Dominicana de Aviacion (DOMINICA)",
        3213 to "Braathens Regional Airlines",
        3214 to "Авиалинии, авиакомпании",
        3215 to "Авиалинии, авиакомпании",
        3216 to "Авиалинии, авиакомпании",
        3217 to "CSA Ceskoslovenske Aerolinie (CSA)",
        3218 to "Авиалинии, авиакомпании",
        3219 to "Compania Panamena de Aviacion (COPA)",
        3220 to "Compania Faucett (COMPANIA)",
        3221 to "Transportes Aeros Militares Ecuatorianos (TAME AIR)",
        3222 to "Command Airways (COMMAND)",
        3223 to "Comair (COMAIR)",
        3224 to "Авиалинии, авиакомпании",
        3225 to "Авиалинии, авиакомпании",
        3226 to "Skyways (SKYWAYS)",
        3227 to "Авиалинии, авиакомпании",
        3228 to "Cayman Airways (CAYMANAIR)",
        3229 to "SAETA (Sociedad Ecuatorianas De Transportes Aereo) (SAETAAIR)",
        3230 to "Авиалинии, авиакомпании",
        3231 to "SAHSA (Servicio Aero de Honduras) (SAHSA)",
        3232 to "Авиалинии, авиакомпании",
        3233 to "Авиалинии, авиакомпании",
        3234 to "Caribbean Airlines (CARIBBEAN)",
        3235 to "Авиалинии, авиакомпании",
        3236 to "Air Arabia Airline (AIR ARAB)",
        3237 to "Авиалинии, авиакомпании",
        3238 to "Авиалинии, авиакомпании",
        3239 to "Bar Harbor Airlines (BARHARBO)",
        3240 to "Bahamasair (BAHAMASA)",
        3241 to "Aviateca (Guatemala) (AVIATECA)",
        3242 to "Avensa (AVENSA)",
        3243 to "Austrian Air Service (AUSTRAIR)",
        3244 to "Авиалинии, авиакомпании",
        3245 to "EasyJet (EASYJET)",
        3246 to "Ryanair (RYANAIR)",
        3247 to "Gol Airlines (GOL)",
        3248 to "Tam Airlines (TAM)",
        3249 to "Авиалинии, авиакомпании",
        3250 to "Авиалинии, авиакомпании",
        3251 to "Авиалинии, авиакомпании",
        3252 to "ALM Antilean Airlines (ALM)",
        3253 to "America West (AMERWEST)",
        3254 to "Trump Airline",
        3256 to "Alaska Airlines Inc. (ALASKA A)",
        3257 to "Авиалинии, авиакомпании",
        3258 to "Авиалинии, авиакомпании",
        3259 to "Авиалинии, авиакомпании",
        3260 to "Spirit Airlines (SPIRIT)",
        3261 to "Air China (AIR CHINA)",
        3262 to "Авиалинии, авиакомпании",
        3263 to "Aero Servicio Carabobo (ASERCA)",
        3264 to "Авиалинии, авиакомпании",
        3265 to "Авиалинии, авиакомпании",
        3266 to "Air Seychelles (AIR SEYC)",
        3267 to "Air Panama International (AIR PANA)",
        3268 to "Авиалинии, авиакомпании",
        3270 to "Авиалинии, авиакомпании",
        3274 to "Авиалинии, авиакомпании",
        3275 to "Авиалинии, авиакомпании",
        3276 to "Авиалинии, авиакомпании",
        3277 to "Авиалинии, авиакомпании",
        3278 to "Авиалинии, авиакомпании",
        3279 to "Авиалинии, авиакомпании",
        3280 to "Air Jamaica (AIR JAMA)",
        3281 to "Air Djibouti (AIR DJIB)",
        3282 to "Air Djibouti (AIR DJIB)",
        3283 to "Авиалинии, авиакомпании",
        3284 to "Авиалинии, авиакомпании",
        3285 to "Aero Peru (AEROPERU)",
        3286 to "Aero Nicaraguenses (AERO NIC)",
        3287 to "Aero Coach Aviation (AEROCOAC)",
        3288 to "Авиалинии, авиакомпании",
        3289 to "Авиалинии, авиакомпании",
        3290 to "Авиалинии, авиакомпании",
        3291 to "Авиалинии, авиакомпании",
        3292 to "Cyprus Airways (CYPRUSA)",
        3293 to "Ecuatoriana (ECUATORI)",
        3294 to "Ethiopian Airlines (ETHIOPIA)",
        3295 to "Kenya Airways (KENYAAIR)",
        3296 to "Air Berlin (AIRBERLIN)",
        3297 to "Tarom Romanian Air Transport (TAROM AIR)",
        3298 to "Air Mauritius (AIRMAURI)",
        3299 to "Wideroes Flyveselskap (WIDEROES)",
        3300 to "Azul Air (AZU)",
        3301 to "Wizz Air (W6)",
        3302 to "Flybe Air",
        3351 to "Affiliated Auto Rental",
        3352 to "American Intl Rent-a-car",
        3353 to "Brooks Rent-a-car",
        3354 to "Action Auto Rental",
        3355 to "Агентства по аренде автомобилей",
        3356 to "Агентства по аренде автомобилей",
        3357 to "Hertz Rent-a-car",
        3358 to "Агентства по аренде автомобилей",
        3359 to "Payless Car Rental",
        3360 to "Snappy Car Rental",
        3361 to "Airways Rent-a-car",
        3362 to "Altra Auto Rental",
        3363 to "Агентства по аренде автомобилей",
        3364 to "Agency Rent-a-car",
        3365 to "Агентства по аренде автомобилей",
        3366 to "Budget Rent-a-car",
        3367 to "Агентства по аренде автомобилей",
        3368 to "Holiday Rent-a-wreck",
        3369 to "Агентства по аренде автомобилей",
        3370 to "Rent-a-wreck",
        3371 to "Агентства по аренде автомобилей",
        3372 to "Агентства по аренде автомобилей",
        3373 to "Агентства по аренде автомобилей",
        3374 to "Агентства по аренде автомобилей",
        3375 to "Агентства по аренде автомобилей",
        3376 to "Ajax Rent-a-car",
        3377 to "Агентства по аренде автомобилей",
        3378 to "Агентства по аренде автомобилей",
        3379 to "Агентства по аренде автомобилей",
        3380 to "Агентства по аренде автомобилей",
        3381 to "Europ Car",
        3382 to "Агентства по аренде автомобилей",
        3383 to "Агентства по аренде автомобилей",
        3384 to "Агентства по аренде автомобилей",
        3385 to "Tropical Rent-a-car",
        3386 to "Showcase Rental Cars",
        3387 to "Alamo Rent-a-car",
        3388 to "Агентства по аренде автомобилей",
        3389 to "Avis Rent-a-car",
        3390 to "Dollar Rent-a-car",
        3391 to "Europe By Car",
        3392 to "Агентства по аренде автомобилей",
        3393 to "National Car Rental",
        3394 to "Kemwell Group Rent-a-car",
        3395 to "Thrifty Rent-a-car",
        3396 to "Tilden Tent-a-car",
        3397 to "Агентства по аренде автомобилей",
        3398 to "Econo-car Rent-a-car",
        3399 to "Amerex Rent-a-Car",
        3400 to "Auto Host Cost Car Rentals",
        3401 to "Агентства по аренде автомобилей",
        3402 to "Агентства по аренде автомобилей",
        3403 to "Агентства по аренде автомобилей",
        3404 to "Агентства по аренде автомобилей",
        3405 to "Enterprise Rent-a-car",
        3406 to "Агентства по аренде автомобилей",
        3407 to "Агентства по аренде автомобилей",
        3408 to "Агентства по аренде автомобилей",
        3409 to "General Rent-a-car",
        3410 to "Агентства по аренде автомобилей",
        3412 to "A-1 Rent-a-car",
        3413 to "Агентства по аренде автомобилей",
        3414 to "Godfrey Natl Rent-a-car",
        3415 to "Агентства по аренде автомобилей",
        3416 to "Агентства по аренде автомобилей",
        3417 to "Агентства по аренде автомобилей",
        3418 to "Агентства по аренде автомобилей",
        3419 to "Alpha Rent-a-car",
        3420 to "Ansa Intl Rent-a-car",
        3421 to "Allstae Rent-a-car",
        3422 to "Агентства по аренде автомобилей",
        3423 to "Avcar Rent-a-car",
        3425 to "Automate Rent-a-car",
        3426 to "Агентства по аренде автомобилей",
        3427 to "Avon Rent-a-car",
        3428 to "Carey Rent-a-car",
        3429 to "Insurance Rent-a-car",
        3430 to "Major Rent-a-car",
        3431 to "Replacement Rent-a-car",
        3432 to "Reserve Rent-a-car",
        3433 to "Ugly Duckling Rent-a-car",
        3434 to "USA Rent-a-car",
        3435 to "Value Rent-a-car",
        3436 to "Autohansa Rent-a-car",
        3437 to "Cite Rent-a-car",
        3438 to "Interent Rent-a-car",
        3439 to "Milleville Rent-a-car",
        3440 to "Via Route Rent-a-Car",
        3441 to "Агентства по аренде автомобилей",
        3501 to "Holiday Inns",
        3502 to "Best Western Hotels",
        3503 to "Sheraton Hotels",
        3504 to "Hilton Hotels",
        3505 to "Forte Hotels",
        3506 to "Golden Tulip Hotels",
        3507 to "Friendship Inns",
        3508 to "Quality Inns",
        3509 to "Marriott Hotels",
        3510 to "Days Inn",
        3511 to "Arabella Hotels",
        3512 to "Inter-continental Hotels",
        3513 to "Westin Hotels",
        3514 to "Отели, мотели, курорты",
        3515 to "Rodeway Inns",
        3516 to "La Quinta Motor Inns",
        3517 to "Americana Hotels",
        3518 to "Sol Hotels",
        3519 to "Pullman International Hotels",
        3520 to "Meridien Hotels",
        3521 to "Crest Hotels (see Forte Hotels)",
        3522 to "Tokyo Hotel",
        3523 to "Pennsula Hotel",
        3524 to "Welcomgroup Hotels",
        3525 to "Dunfey Hotels",
        3526 to "Отели, мотели, курорты",
        3527 to "Downtowner-passport Hotel",
        3528 to "Red Lion Hotels",
        3529 to "Cp Hotels",
        3530 to "Renaissance Hotels",
        3531 to "Astir Hotels",
        3532 to "Sun Route Hotels",
        3533 to "Hotel Ibis",
        3534 to "Southern Pacific Hotels",
        3535 to "Hilton International",
        3536 to "Amfac Hotels",
        3537 to "Ana Hotel",
        3538 to "Concorde Hotels",
        3539 to "Отели, мотели, курорты",
        3540 to "Iberotel Hotels",
        3541 to "Hotel Okura",
        3542 to "Royal Hotels",
        3543 to "Four Seasons Hotels",
        3544 to "Ciga Hotels",
        3545 to "Shangri-la International",
        3546 to "Отели, мотели, курорты",
        3547 to "Отели, мотели, курорты",
        3548 to "Hoteles Melia",
        3549 to "Auberge Des Governeurs",
        3550 to "Regal 8 Inns",
        3551 to "Отели, мотели, курорты",
        3552 to "Coast Hotels",
        3553 to "Park Inns International",
        3554 to "Отели, мотели, курорты",
        3555 to "Отели, мотели, курорты",
        3556 to "Отели, мотели, курорты",
        3557 to "Отели, мотели, курорты",
        3558 to "Jolly Hotels",
        3559 to "Отели, мотели, курорты",
        3560 to "Отели, мотели, курорты",
        3561 to "Отели, мотели, курорты",
        3562 to "Comfort Inns",
        3563 to "Journey’s End Motls",
        3564 to "Отели, мотели, курорты",
        3565 to "Relax Inns",
        3566 to "Отели, мотели, курорты",
        3567 to "Отели, мотели, курорты",
        3568 to "Ladbroke Hotels",
        3569 to "Отели, мотели, курорты",
        3570 to "Forum Hotels",
        3571 to "Отели, мотели, курорты",
        3572 to "Miyako Hotels",
        3573 to "Sandman Hotels",
        3574 to "Venture Inns",
        3575 to "Vagabond Hotels",
        3576 to "Отели, мотели, курорты",
        3577 to "Mandarin Oriental Hotel",
        3578 to "Отели, мотели, курорты",
        3579 to "Hotel Mercure",
        3580 to "Отели, мотели, курорты",
        3581 to "Delta Hotel",
        3582 to "Отели, мотели, курорты",
        3583 to "Sas Hotels",
        3584 to "Princess Hotels International",
        3585 to "Hungar Hotels",
        3586 to "Sokos Hotels",
        3587 to "Doral Hotels",
        3588 to "Helmsley Hotels",
        3589 to "Отели, мотели, курорты",
        3590 to "Fairmont Hotels",
        3591 to "Sonesta Hotels",
        3592 to "Omni Hotels",
        3593 to "Cunard Hotels",
        3594 to "Отели, мотели, курорты",
        3595 to "Hospitality International",
        3596 to "Отели, мотели, курорты",
        3597 to "Отели, мотели, курорты",
        3598 to "Regent International Hotels",
        3599 to "Pannonia Hotels",
        3600 to "Отели, мотели, курорты",
        3601 to "Отели, мотели, курорты",
        3602 to "Отели, мотели, курорты",
        3603 to "Noah’s Hotels",
        3604 to "Отели, мотели, курорты",
        3605 to "Отели, мотели, курорты",
        3606 to "Отели, мотели, курорты",
        3607 to "Отели, мотели, курорты",
        3608 to "Отели, мотели, курорты",
        3609 to "Отели, мотели, курорты",
        3610 to "Отели, мотели, курорты",
        3611 to "Отели, мотели, курорты",
        3612 to "Movenpick Hotels",
        3613 to "Отели, мотели, курорты",
        3614 to "Отели, мотели, курорты",
        3615 to "Travelodge",
        3616 to "Отели, мотели, курорты",
        3617 to "Отели, мотели, курорты",
        3618 to "Отели, мотели, курорты",
        3619 to "Отели, мотели, курорты",
        3620 to "Telford International",
        3621 to "Отели, мотели, курорты",
        3622 to "Merlin Hotels",
        3623 to "Dorint Hotels",
        3624 to "Отели, мотели, курорты",
        3625 to "Hotle Universale",
        3626 to "Prince Hotels",
        3627 to "Отели, мотели, курорты",
        3628 to "Отели, мотели, курорты",
        3629 to "Dan Hotels",
        3630 to "Отели, мотели, курорты",
        3631 to "Отели, мотели, курорты",
        3632 to "Отели, мотели, курорты",
        3633 to "Rank Hotels",
        3634 to "Swissotel",
        3635 to "Reso Hotels",
        3636 to "Sarova Hotels",
        3637 to "Ramada Inns",
        3638 to "Ho Jo Inn",
        3639 to "Mount Charlotte Thistle",
        3640 to "Hyatt Hotel",
        3641 to "Sofitel Hotels",
        3642 to "Novotel Hotels",
        3643 to "Steigenberger Hotels",
        3644 to "Econo Lodges",
        3645 to "Queens Moat Houses",
        3646 to "Swallow Hotels",
        3647 to "Husa Hotels",
        3648 to "De Vere Hotels",
        3649 to "Radisson Hotels",
        3650 to "Red Rook Inns",
        3651 to "Imperial London Hotel",
        3652 to "Embassy Hotels",
        3653 to "Penta Hotels",
        3654 to "Loews Hotels",
        3655 to "Scandic Hotels",
        3656 to "Sara Hotels",
        3657 to "Oberoi Hotels",
        3658 to "Otani Hotels",
        3659 to "Taj Hotels International",
        3660 to "Knights Inns",
        3661 to "Metropole Hotels",
        3662 to "Отели, мотели, курорты",
        3663 to "Hoteles El Presidents",
        3664 to "Flag Inn",
        3665 to "Hampton Inns",
        3666 to "Stakis Hotels",
        3667 to "Отели, мотели, курорты",
        3668 to "Maritim Hotels",
        3669 to "Отели, мотели, курорты",
        3670 to "Arcard Hotels",
        3671 to "Arctia Hotels",
        3672 to "Campaniel Hotels",
        3673 to "Ibusz Hotels",
        3674 to "Rantasipi Hotels",
        3675 to "Interhotel Cedok",
        3676 to "Отели, мотели, курорты",
        3677 to "Climat De France Hotels",
        3678 to "Cumulus Hotels",
        3679 to "Danubius Hotel",
        3680 to "Отели, мотели, курорты",
        3681 to "Adams Mark Hotels",
        3682 to "Allstar Inns",
        3683 to "Отели, мотели, курорты",
        3684 to "Budget Host Inns",
        3685 to "Budgetel Hotels",
        3686 to "Suisse Chalets",
        3687 to "Clarion Hotels",
        3688 to "Compri Hotels",
        3689 to "Consort Hotels",
        3690 to "Courtyard By Marriott",
        3691 to "Dillion Inns",
        3692 to "Doubletree Hotels",
        3693 to "Drury Inns",
        3694 to "Economy Inns Of America",
        3695 to "Embassy Suites",
        3696 to "Exel Inns",
        3697 to "Farfield Hotels",
        3698 to "Harley Hotels",
        3699 to "Midway Motor Lodge",
        3700 to "Motel 6",
        3701 to "Guest Quarters (formally Pickett Suite Hotels)",
        3702 to "The Registry Hotels",
        3703 to "Residence Inns",
        3704 to "Royce Hotels",
        3705 to "Sandman Inns",
        3706 to "Shilo Inns",
        3707 to "Shoney’s Inns",
        3708 to "Отели, мотели, курорты",
        3709 to "Super8 Motels",
        3710 to "The Ritz Carlton Hotels",
        3711 to "Flag Inns (Ausralia)",
        3712 to "Golden Chain Hotel",
        3713 to "Quality Pacific Hotel",
        3714 to "Four Seasons Hotel (Australia)",
        3715 to "Farifield Inn",
        3716 to "Carlton Hotels",
        3717 to "City Lodge Hotels",
        3718 to "Karos Hotels",
        3719 to "Protea Hotels",
        3720 to "Southern Sun Hotels",
        3721 to "Hilton Conrad",
        3722 to "Wyndham Hotel And Resorts",
        3723 to "Rica Hotels",
        3724 to "Iner Nor Hotels",
        3725 to "Seaines Planation",
        3726 to "Rio Suites",
        3727 to "Broadmoor Hotel",
        3728 to "Bally’s Hotel And Casino",
        3729 to "John Ascuaga’s Nugget",
        3730 to "Mgm Grand Hotel",
        3731 to "Harrah’s Hotels And Casinos",
        3732 to "Opryland Hotel",
        3733 to "Boca Raton Resort",
        3734 to "Harvey/bristol Hotels",
        3735 to "Отели, мотели, курорты",
        3736 to "Colorado Belle/Edgewater Resort",
        3737 to "Riviera Hotel And Casino",
        3738 to "Tropicana Resort And Casino",
        3739 to "Woodside Hotels And Resorts",
        3740 to "Townplace Suites",
        3741 to "Millenium Broadway Hotel",
        3742 to "Club Med",
        3743 to "Biltmore Hotel And Suites",
        3744 to "Carefree Resorts",
        3745 to "St. Regis Hotel",
        3746 to "The Eliot Hotel",
        3747 to "Clubcorp/club Resorts",
        3748 to "Welesley Inns",
        3749 to "The Beverly Hills Hotel",
        3750 to "Crowne Plaza Hotels",
        3751 to "Homewood Suites",
        3752 to "Peabody Hotels",
        3753 to "Greenbriah Resorts",
        3754 to "Amelia Island Planation",
        3755 to "The Homestead",
        3756 to "South Seas Resorts",
        3757 to "Отели, мотели, курорты",
        3758 to "Отели, мотели, курорты",
        3759 to "Отели, мотели, курорты",
        3760 to "Отели, мотели, курорты",
        3761 to "Отели, мотели, курорты",
        3762 to "Отели, мотели, курорты",
        3763 to "Отели, мотели, курорты",
        3764 to "Отели, мотели, курорты",
        3765 to "Отели, мотели, курорты",
        3766 to "Отели, мотели, курорты",
        3767 to "Отели, мотели, курорты",
        3768 to "Отели, мотели, курорты",
        3769 to "Отели, мотели, курорты",
        3770 to "Отели, мотели, курорты",
        3771 to "Отели, мотели, курорты",
        3772 to "Отели, мотели, курорты",
        3773 to "Отели, мотели, курорты",
        3774 to "Отели, мотели, курорты",
        3775 to "Отели, мотели, курорты",
        3776 to "Отели, мотели, курорты",
        3777 to "Отели, мотели, курорты",
        3778 to "Отели, мотели, курорты",
        3779 to "Отели, мотели, курорты",
        3780 to "Отели, мотели, курорты",
        3781 to "Отели, мотели, курорты",
        3782 to "Отели, мотели, курорты",
        3783 to "Отели, мотели, курорты",
        3784 to "Отели, мотели, курорты",
        3785 to "Отели, мотели, курорты",
        3786 to "Отели, мотели, курорты",
        3787 to "Отели, мотели, курорты",
        3788 to "Отели, мотели, курорты",
        3789 to "Отели, мотели, курорты",
        3790 to "Отели, мотели, курорты",
        3791 to "Отели, мотели, курорты",
        3792 to "Отели, мотели, курорты",
        3793 to "Отели, мотели, курорты",
        3794 to "Отели, мотели, курорты",
        3795 to "Отели, мотели, курорты",
        3796 to "Отели, мотели, курорты",
        3797 to "Отели, мотели, курорты",
        3798 to "Отели, мотели, курорты",
        3799 to "Отели, мотели, курорты",
        3800 to "Homestead Suites",
        3801 to "Wilderness Hotel and Resort",
        3802 to "The Palace Hotel",
        3803 to "The Wigwam Golf Resort and Spa",
        3804 to "The Diplomat Country Club and Spa",
        3805 to "The Atlantic",
        3806 to "Princeville Resort",
        3807 to "Element",
        3808 to "LXR (Luxury Resorts)",
        3809 to "Settle Inn",
        3810 to "La Costa Resort",
        3811 to "Premier Travel Inns",
        3812 to "Hyatt Place",
        3813 to "Hotel Indigo",
        3814 to "The Roosevelt Hotel NY",
        3815 to "Nickelodeon Family Suites by Holiday Inn",
        3816 to "Home2Suites",
        3817 to "Affinia",
        3818 to "Mainstay Suites",
        3819 to "Oxford Suites",
        3820 to "Jumeirah Essex House",
        3821 to "Caribe Royal",
        3822 to "Crossland",
        3823 to "Grand Sierra Resort",
        3824 to "Aria",
        3825 to "Vdara",
        3826 to "Autograph",
        3827 to "Galt House",
        3828 to "Cosmopolitan of Las Vegas",
        3829 to "Country Inn By Carlson",
        3830 to "Park Plaza Hotel",
        3831 to "Waldorf",
        3832 to "Curio Hotels",
        3833 to "Canopy",
        3834 to "Baymont Inn & Suites",
        3835 to "Dolce Hotels and Resorts",
        3836 to "Hawthorn by Wyndham",
        3837 to "Hoshino Resorts",
        3838 to "Kimpton Hotels",
        3882 to "Инкассация чека (обналичивание)",
        4011 to "Железные дороги – перевозка грузов",
        4111 to "Пассажирские перевозки - пригородные и местные пригородные рейсы, включая паромы",
        4112 to "Пассажирские железнодорожные перевозки",
        4119 to "Услуги скорой помощи",
        4121 to "Лимузины и такси",
        4131 to "Автобусные линии",
        4214 to "Агентства по автотранспортным перевозкам, местные/ дальные автогрузоперевозки, компании попереезду и хранению, местная доставка",
        4215 to "Услуги курьера – по воздуху и на земле, агентство по отправке грузов",
        4225 to "Складское хранение общественного пользования –сельскохозяйственных продуктов, охлаждаемые продукты, хранение предметов домашнего обихода",
        4304 to "Категория неизвестна",
        4411 to "Круизные линии",
        4457 to "Аренда и лизинг суден",
        4468 to "Пристани для яхт, их обслуживание и поставка расходных материалов",
        4511 to "Авиалинии, авиакомпании - нигде более не классифицированные",
        4582 to "Аэропорты, терминалы аэропортов, лётные поля",
        4722 to "Туристические агентства и организаторы экскурсий",
        4723 to "Пакетные туроператоры - только Германия",
        4729 to "Услуги пассажирских перевозок – нигде более не классифицированные",
        4784 to "Платные дороги и мосты",
        4785 to "Категория неизвестна",
        4789 to "Услуги пассажирских перевозок – нигде более не классифицированные",
        4812 to "Телекоммуникационное оборудование, включая продажу телефонов",
        4813 to "Торговые точки телеком клавишного ввода, предлагающие единичные локальные и дальние телефонные звонки, используя центральный номер доступа без разговора с оператором и используя код доступа",
        4814 to "Телекоммуникационные услуги",
        4815 to "МастерФон телефонные услуги – Ежемесячное составление телефонных счетов",
        4816 to "Компьютерные сети, информационные услуги",
        4821 to "Услуги телеграфа",
        4829 to "Денежные переводы",
        4899 to "Кабельные и другие платные телевизионные услуги",
        4900 to "Жилищно-коммунальные услуги",
        5013 to "Поставщики грузовиков и запчастей",
        5021 to "Офисная и торговая мебель",
        5039 to "Строительные материалы – нигде более не классифицированные",
        5044 to "Офисное, фотографическое, фотокопировальное, и микрофильмирующее оборудование",
        5045 to "Компьютеры, периферийное компьютерное оборудование, программное обеспечение",
        5046 to "Коммерческое оборудование – нигде более не классифицированное",
        5047 to "Стоматологическое / лабораторное / медицинское / офтальмологическое оборудование и материалы для больниц",
        5051 to "Центры и офисы работ по металлу",
        5065 to "Электрические части и оборудование",
        5072 to "Оборудование и сопутствующие материалы для технического обеспечения",
        5074 to "Оборудование для водопровода и отопительной системы",
        5085 to "Промышленное оборудование –нигде более не классифицированное",
        5094 to "Драгоценные камни и металлы, часы и ювелирные изделия",
        5099 to "Товары длительного пользования – нигде более не классифицированные",
        5111 to "Канцелярия, офисные сопутствующие товары, бумага для печатания и письма",
        5122 to "Лекарства, их распространители, аптеки",
        5131 to "Штучные товары, галантерея и другие текстильные товары",
        5137 to "Мужская, женская и детская спецодежда",
        5139 to "Спец-обувь",
        5169 to "Химикалии и смежные вещества - нигде более не классифицированные",
        5172 to "Нефть и нефтепродукты",
        5192 to "Книги, периодические издания и газеты",
        5193 to "Принадлежности для флористов, питомник и цветы",
        5198 to "Лакокрасочная продукция и сопровождающие товары",
        5199 to "Товары недлительного пользования - нигде более не классифицированные",
        5200 to "Товары для дома",
        5211 to "Лесо- и строительный материал",
        5231 to "Розничная продажа стекла, красок и обоев",
        5251 to "Скобяные товары в розницу",
        5261 to "Садовые принадлежности (в том числе для ухода за газонами) в розницу",
        5262 to "Маркетплейсы",
        5271 to "Продажа жилых фургонов",
        5292 to "Категория неизвестна",
        5295 to "Категория неизвестна",
        5297 to "Retail Internet Volume",
        5298 to "Internet Shopping Grocery Store",
        5300 to "Оптовики",
        5309 to "Беспошлинные магазины Duty Free",
        5310 to "Магазины, торгующие по сниженным ценам",
        5311 to "Универмаги",
        5331 to "Универсальные магазины",
        5399 to "Различные товары общего назначения",
        5411 to "Бакалейные магазины, супермаркеты",
        5412 to "Гибридные супермаркеты",
        5415 to "Категория неизвестна",
        5422 to "Продажа свежего и мороженого мяса",
        5441 to "Кондитерские",
        5451 to "Продажа молочных продуктов в розницу",
        5462 to "Булочные",
        5499 to "Различные продовольственные магазины - нигде более не классифицированные",
        5511 to "Легковой и грузовой транспорт – продажа, сервис, ремонт, запчасти и лизинг.",
        5521 to "Продажа легковых и грузовых автомобилей (только подержанных)",
        5531 to "Автомагазины и товары для дома",
        5532 to "Автошины",
        5533 to "Автозапчасти и аксессуары",
        5541 to "Заправочные станции (с вспомогательными услугами или без)",
        5542 to "Автоматические заправочные станции",
        5551 to "Продажа лодок",
        5552 to "Зарядка электромобилей",
        5561 to "Дома- автоприцепы, жилые неразборные и грузовые прицепы",
        5571 to "Продажа мотоциклов",
        5592 to "Продажа домов на колесах",
        5598 to "Продажа снегоходов",
        5599 to "Продажа различного рода автомобилей, авиа- и с/х оборудования - нигде более не классифицированные",
        5611 to "Мужская одежда и аксессуары, включая одежду для мальчиков",
        5621 to "Готовая женская одежда",
        5631 to "Аксессуары для женщин",
        5641 to "Детская одежда, включая одежду для самых маленьких",
        5651 to "Одежда для всей семьи",
        5655 to "Спортивная одежда, одежда для верховой езды и езды на мотоцикле",
        5661 to "Обувные магазины",
        5681 to "Изготовление и продажа меховых изделий",
        5691 to "Магазины мужской и женской одежды",
        5697 to "Услуги по переделке, починке и пошиву одежды",
        5698 to "Парики и накладки из искусственных волос",
        5699 to "Различные магазины одежды и аксессуаров",
        5712 to "Оборудование, мебель и бытовые принадлежности (кроме электрооборудования)",
        5713 to "Покрытия для пола",
        5714 to "Ткани, обивочный материал, гардины и портьеры, жалюзи",
        5715 to "Оптовые продавцы алкоголя",
        5718 to "Продажа каминов, экранов для каминов и аксессуаров",
        5719 to "Различные специализированные магазины бытовых принадлежностей",
        5722 to "Бытовое оборудование",
        5732 to "Продажа электронного оборудования",
        5733 to "Продажа музыкальных инструментов, фортепиано, нот.",
        5734 to "Продажа компьютерного программного обеспечения",
        5735 to "Магазины звукозаписи",
        5811 to "Поставщики провизии",
        5812 to "Места общественного питания, рестораны",
        5813 to "Бары, коктейль-бары, дискотеки, ночные клубы и таверны – места продажи алкогольных напитков",
        5814 to "Фастфуд",
        5815 to "Цифровые товары - аудиовизуальные медиа, включая книги, фильмы и музыку",
        5816 to "Цифровые товары – игры",
        5817 to "Цифровые товары - приложения (кроме игр)",
        5818 to "Цифровые товары - мультикатегория",
        5912 to "Аптеки",
        5921 to "Магазины с продажей спиртных напитков навынос",
        5931 to "Секонд-хенды, магазины б/у товаров, комиссионки",
        5932 to "Антикварные магазины – продажа, ремонт и услуги реставрации",
        5933 to "Ломбарды",
        5935 to "Уничтожение и сбор остатков",
        5937 to "Магазины репродукций и антиквариата",
        5940 to "Веломагазины – продажа и обслуживание",
        5941 to "Спорттовары",
        5942 to "Книжные магазины",
        5943 to "Магазины офисных, школьных принадлежностей, канцтоваров",
        5944 to "Часы, ювелирные и серебряные изделия",
        5945 to "Игрушки, игры и хобби-товары",
        5946 to "Магазины фотооборудования и фотоприборов",
        5947 to "Магазины открыток, подарков, новинок и сувениров",
        5948 to "Магазины кожаных изделий, дорожных принадлежностей",
        5949 to "Магазины ткани, ниток, рукоделия, шитья",
        5950 to "Магазины хрусталя и изделий из стекла",
        5960 to "Прямой маркетинг – страховые услуги",
        5961 to "Заказы по почте, включая заказы по каталогу",
        5962 to "Прямой маркетинг – услуги, относящиеся к туризму",
        5963 to "Продажи от двери до двери",
        5964 to "Прямой маркетинг – торговля по каталогам",
        5965 to "Прямой маркетинг – комбинированный каталог и розничные продавцы",
        5966 to "Прямой маркетинг - исходящий телемаркетинг",
        5967 to "Прямой маркетинг – входящий телемаркетинг",
        5968 to "Прямой маркетинг – Продажа по подписке",
        5969 to "Прямой маркетинг – другие торговые точки прямого маркетинга (нигде более не классифицированные)",
        5970 to "Магазины художественных и ремесляных изделий",
        5971 to "Галереи и художественные посредники",
        5972 to "Магазины монет и марок (филателические и нумизматические)",
        5973 to "Магазины религиозных товаров",
        5975 to "Слуховые аппараты – продажа, сервис, снабжение",
        5976 to "Ортопедические товары",
        5977 to "Магазины косметики",
        5978 to "Магазины печатающих устройств – аренда, продажа, услуги",
        5983 to "Поставщики топлива – уголь, мазут, сжиженная нефть, древесина",
        5992 to "Флористика",
        5993 to "Табачные магазины",
        5994 to "Дилеры по продаже печатной продукции",
        5995 to "Зоомагазины",
        5996 to "Плавательные бассейны – продажа и снабжение",
        5997 to "Магазины электрических бритвенных принадлежностей – распродажа и услуги.",
        5998 to "Магазины палаток и навесов",
        5999 to "Различные магазины и специальные розничные магазины",
        6010 to "Финансовые учреждения – выдача наличных в кассе",
        6011 to "Финансовые учреждения – снятие наличных автоматически",
        6012 to "Финансовые учреждения – торговля и услуги",
        6022 to "Financial Institution (RCL Internal)",
        6023 to "State Banks (RCL Internal)",
        6025 to "National Banks (RCL Internal)",
        6026 to "National Banks Non Federal (RCL Internal)",
        6028 to "Unincorporated Private Banks (RCL Internal)",
        6050 to "Квази-Кэш – Финансовые учреждения",
        6051 to "Квази-Кэш – Нефинансовые учреждения",
        6211 to "Услуги брокеров на рынке ценных бумаг",
        6300 to "Услуги страховых компаний",
        6381 to "Страховые премии",
        6399 to "Страхование - нигде более не классифицированные",
        6513 to "Агенты недвижимости и менеджеры - Аренда",
        6529 to "Удалённое пополнение предоплаченной карты - Финансовые организации",
        6530 to "Удалённое пополнение предоплаченной карты - Торговая точка",
        6531 to "Оплата услуг – денежные переводы",
        6532 to "Платежная операция - финансовое учреждение",
        6533 to "Платежная операция - продавец",
        6534 to "Денежный перевод - финансовое учреждение",
        6535 to "Права требования на ценности — Финансовые организации",
        6536 to "Денежные переводы с карты на карту – зачисление (внутри страны)",
        6537 to "Денежные переводы с карты на карту – зачисление (между странами)",
        6538 to "Денежные переводы с карты на карту – списание",
        6539 to "Транзакция по финансированию (исключая MoneySend)",
        6540 to "Пополнение небанковских предоплаченных карт, счетов",
        6611 to "Переплата (авансовые платежи)",
        6760 to "Облигации сберегательного займа",
        7011 to "Отели и мотели - нигде более не классифицированные",
        7012 to "Тайм-шер",
        7032 to "Рекреационные и спортивные лагеря",
        7033 to "Кемпинги и трейлер-парки",
        7210 to "Услуги по уборке и прачечной",
        7211 to "Услуги прачечной - семейные и коммерческие",
        7216 to "Химчистка",
        7217 to "Чистка ковров и обивки мебели",
        7221 to "Фотостудии",
        7230 to "Парикмахерские и салоны красоты",
        7251 to "Чистка шляп, ремонт и полировка обуви",
        7261 to "Ритуальные услуги и крематории",
        7273 to "Знакомства",
        7276 to "Служба налоговой подготовки",
        7277 to "Долги, брак, личные вопросы - консультирование",
        7278 to "Услуги покупок/шоппинга",
        7280 to "Пациент больницы – вывод личных средств",
        7296 to "Сдача в аренду костюмов, униформы, простой одежды",
        7297 to "Массажные салоны",
        7298 to "Салоны красоты и здоровья",
        7299 to "Различные услуги - нигде более не классифицированные",
        7311 to "Рекламные услуги",
        7321 to "Кредитные бюро",
        7322 to "Агентства взыскания долгов",
        7332 to "Услуги синьки и фотокопирования",
        7333 to "Коммерческое искусство, графика, фотография",
        7338 to "Быстрое копирование, репродуцирование и услуги по созданию чертежей",
        7339 to "Услуги стенографии и секретарского дела",
        7342 to "Дезинсекция, дезинфекция и дератизация",
        7349 to "Уборка и техническое обслуживание зданий и помещений",
        7361 to "Агентства по трудоустройству, временные справочные службы",
        7372 to "Программирование, обработка данных, проектирование интегрированных систем",
        7375 to "Информационно-поисковые услуги",
        7379 to "Ремонт компьютеров",
        7389 to "Бизнес услуги – нигде более не классифицированные",
        7392 to "Услуги по консультированию, управлению и связям с общественностью",
        7393 to "Детективные агентства, охранные агентства, службы безопасности, включая бронированные автомобили, сторожевых собак",
        7394 to "Аренда оборудования и лизинговые услуги, аренда мебели, прокат инструментов",
        7395 to "Фотостудии, фотолаборатории",
        7399 to "Бизнес услуги – нигде более не классифицированные",
        7511 to "Стоянка грузового транспорта",
        7512 to "Прокат автомобилей",
        7513 to "Прокат аксессуаров для трэйлеров и грузовиков.",
        7519 to "Прокат домиков на колесах, аксессуары к наземному транспорту.",
        7523 to "Паркинги и гаражи",
        7531 to "Кузовной ремонт автомобилей",
        7534 to "Шиномонтаж и вулканизация",
        7535 to "Покраска автомобилей",
        7538 to "Автосервисы",
        7542 to "Автомойки",
        7549 to "Услуги буксировки и эвакуации",
        7622 to "Ремонт электроники",
        7623 to "Ремонт кондиционеров и холодильников",
        7629 to "Ремонт электрооборудования и малой бытовой техники",
        7631 to "Центры ремонта часов и чистки ювелирных изделий",
        7641 to "Обивка, ремонт и отделка мебели",
        7692 to "Ремонт с помощью сварки",
        7699 to "Ремонтные услуги – нигде более не классифицированные",
        7800 to "Государственные лотереи (только США)",
        7801 to "Азартные игры в интернете (только США)",
        7802 to "Лошадиные / собачьи бега (только США)",
        7829 to "Производство и распространение кинофильмов и видеокассет",
        7832 to "Кинотеатры",
        7833 to "Экспресс-оплата – Кинотеатр",
        7841 to "Видеопрокат",
        7911 to "Танцевальные залы, школы и студии",
        7922 to "Театральные продюсеры (кроме кинофильмов), билетные агентства",
        7929 to "Музыкальные группы, оркестры и прочие развлекательные услуги",
        7932 to "Бильярд-клубы",
        7933 to "Боулинг",
        7941 to "Атлетические поля, коммерческие виды спорта, профессиональные спортивные клубы, промоутеры спорта",
        7991 to "Туристические достопримечательности и выставки",
        7992 to "Публичные поля для гольфа",
        7993 to "Принадлежности для видеоигр",
        7994 to "Клубы видеоигр",
        7995 to "Азартные игры",
        7996 to "Парки аттракционов, карнавалы, цирки, гадалки",
        7997 to "Клубы – загородные клубы, членство (отдых, спорт), частные поля для гольфа",
        7998 to "Аквариумы, дельфинарии, зоопарки и морские парки",
        7999 to "Услуги отдыха - нигде более не классифицированные",
        8011 to "Врачи – нигде более не классифицированные",
        8021 to "Стоматологи, ортодонты",
        8031 to "Остеопаты",
        8041 to "Мануальные терапевты",
        8042 to "Оптометристы, офтальмологи",
        8043 to "Оптика, оптические товары и очки",
        8044 to "Оптические товары и очки (TSYS)",
        8049 to "Ортопеды",
        8050 to "Услуги персонального ухода",
        8062 to "Больницы",
        8071 to "Стоматологические и медицинские лаборатории",
        8099 to "Медицинские работники, медицинские услуги – нигде более не классифицированные",
        8111 to "Адвокаты, юридические услуги",
        8211 to "Начальная и средняя школы",
        8220 to "Колледжи, университеты, профессиональные училища и техникумы",
        8241 to "Дистанционные школы",
        8244 to "Бизнес / секретарские школы",
        8249 to "Профессиональные школы и училища",
        8299 to "Образовательные услуги, нигде более не классифицированные",
        8351 to "Услуги ухода за детьми",
        8398 to "Благотворительные организации и социальные службы - сбор средств",
        8641 to "Гражданские, социальные и братские ассоциации",
        8651 to "Политические организации",
        8661 to "Религиозные организации",
        8664 to "Категория неизвестна",
        8675 to "Автомобильные ассоциации",
        8699 to "Членские организации – нигде более не классифицированные",
        8734 to "Испытательные лаборатории (немедицинские)",
        8743 to "Испытательные лаборатории (немедицинские)",
        8911 to "Архитектурные, инженерные и геодезические услуги",
        8931 to "Аудит и бухгалтерский учет",
        8999 to "Профессиональные услуги - нигде более не классифицированные",
        9034 to "I-Purchasing Pilot",
        9211 to "Судебные выплаты, включая алименты и детскую поддержку",
        9222 to "Штрафы",
        9223 to "Платежи по залогам и облигациям",
        9311 to "Налоговые платежи",
        9399 to "Государственные услуги - нигде более не классифицированные",
        9401 to "I-Purchasing Pilot",
        9402 to "Почтовые услуги – только государственные",
        9405 to "Внутригосударственные закупки - только государственные",
        9406 to "Государственные лотереи (кроме США)",
        9411 to "Платежи по государственному займу",
        9700 to "Automated Referral Service (только VISA)",
        9701 to "Служба проверки учетных данных Visa (только VISA)",
        9702 to "Аварийные службы GCAS (только VISA)",
        9751 to "Супермаркеты (Великобритания)",
        9752 to "Автозаправочные станции (Великобритания)",
        9754 to "Лошадиные / собачьи бега (только США)",
        9950 to "Покупки внутри компании",
        9999 to "Категория неизвестна",
    )
}
